modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="horse_auction"
version="1.0"
displayName="Horse auction"
logoFile="logo.png"
authors="Komti23"


[[dependencies.horse_auction]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"
